networks:
  cross-dsp:
    driver: bridge

services:

  backend:
    image: khutsokobela/cross-dsp-backend:latest
    ports:
      - "5080:5080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_HTTP_PORTS=5080
    networks:
      - cross-dsp

  react-frontend:
    image: khutsokobela/cross-dsp-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cross-dsp
