networks:
  cross-dsp:
    driver: bridge

services:

  backend:
    image: khutsokobela/cross-dsp-backend:latest
    ports:
      - "5080:5080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_HTTP_PORTS=5080
      - GoogleOAuth2Options__ClientId=$GOOGLE_CLIENT_ID
      - GoogleOAuth2Options__ClientSecret=$GOOGLE_CLINET_SECRET
      - SpotifyOAuth2Options__ClientId=$SPOTIFY_CLIENT_ID
      - SpotifyOAuth2Options__ClientSecret=$SPOTIFY_CLIENT_SECRET
    networks:
      - cross-dsp

  react-frontend:
    image: khutsokobela/cross-dsp-frontend:latest
    ports:
      - "3080:80"
    depends_on:
      - backend
    networks:
      - cross-dsp
