networks:
  cross-dsp:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev 
    ports:
      - "5080:5080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_HTTP_PORTS=5080
    networks:
      - cross-dsp
  react-frontend:
    build:
      context: ./frontend/cross-dsp-web-app
      dockerfile: Dockerfile.dev 
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:5080
    volumes:
      - ./frontend/cross-dsp-web-app:/app
    depends_on:
      - backend
    networks:
      - cross-dsp